//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageIndex
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_dataContext : DbContext
    {
        public db_dataContext()
            : base("name=db_dataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<files> files { get; set; }
        public virtual DbSet<folders> folders { get; set; }
        public virtual DbSet<mediaTypes> mediaTypes { get; set; }
        public virtual DbSet<storage> storage { get; set; }
    }
}
